### ISSUE TITLE
Error running the main function

### ISSUE THREAD

**Issue by MaxPoon** [lipiji/PG_BOW_DEMO#3]
When I run the main function, the error below is found.

Error using svmtrain (line 233)
Y must be a vector or a character array.

Error in do_classification_rbf_svm (line 38)
model=svmtrain(train_labels, train_data, options);

Error in main (line 51)
do_classification_rbf_svm

Any solutions to correct this?

**Comment by lipiji** [comment]
compile libsvm again.
