### ISSUE TITLE
Error loading sift features

### ISSUE THREAD

**Issue by razia-b** [lipiji/PG_BOW_DEMO#4]
CalculateDictionary.m stops at line 31 and gives error:
unable to load file PG_BOW_DEMO\data\local\00000001\sift_features'. No such file or directory.
would you help, at which step sift_features are supposed to be created?
any solution to correct?

**Comment by lipiji** [comment]
have you modify the related path according to the ReadMe?

**Comment by razia-b** [comment]
Yes I have modified the related paths accordingly. 

It’s the sift_features which should have been created at mentioned path(PG_BOW_DEMO\data\local\00000001\) before the execution of line 31 In CalculateDictionary.m.  

But at my machine PG_BOW_DEMO\data\local\00000001 is empty. So I get error:

unable to load file PG_BOW_DEMO\data\local\00000001\sift_features'. No such file or directory.

**Comment by lipiji** [comment]
What is the path looks like?
You'd better use the absolute path of PG_BOW_DEMO.

**Comment by razia-b** [comment]
It is fixed now.
The problem was not the path, it was some lines of code in CalculateDictionary.m falsely determined the sift_features have already been created when they were not. 

Now I got everything working but at the end the computed accuracy in all methods is shown -1.

![error blank](https://cloud.githubusercontent.com/assets/8632371/24042999/476fa29a-0b36-11e7-99ca-01142ed76790.png)

i am getting empty matrix in svmpredict.
any guess?

**Comment by razia-b** [comment]
finally, i got it working.
good work lipiji!

**Comment by Xiao-G1023** [comment]
@razia-b Hi, friend! I encountered the same problem: unable to read file '...\PG_BOW_DEMO\data\local\00000001\sift_features'. No such file or directory.
Could you please share your experience on the sulution? Best wishes for you!
